<?php
require_once __DIR__ . '/../includes/auth.php';
require_login();
$pageTitle = $pageTitle ?? 'Dashboard';
$activePage = $activePage ?? 'dashboard';
$user = current_user();
$flashMessage = pull_flash();
$nonce = base64_encode(random_bytes(16));
header('X-Content-Type-Options: nosniff'); header('X-Frame-Options: SAMEORIGIN'); header('Referrer-Policy: strict-origin-when-cross-origin'); header("Content-Security-Policy: default-src 'self' https://quickchart.io; img-src 'self' data: https://quickchart.io; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'");
$nav = $user['role'] === 'resident' ? ['portal' => ['My portal', '♙'], 'announcements' => ['Announcements', '◈'], 'privacy' => ['Privacy requests', '⌘'], 'notifications' => ['Notifications', '♢']] : ['dashboard' => ['Dashboard', '▦'], 'residents' => ['Residents', '♙'], 'documents' => ['Document issuance', '▤'], 'blotters' => ['Blotter records', '▣'], 'accounts' => ['Resident accounts', '♧'], 'staff' => ['Staff accounts', '♚'], 'feedback' => ['Feedback', '♡'], 'reports' => ['Reports & analytics', '▥'], 'announcements' => ['Announcements', '◈'], 'notifications' => ['Notifications', '♢'], 'audit' => ['Audit log', '⌁'], 'privacy_admin' => ['Privacy requests', '⌘']];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= h($pageTitle) ?> · Barangay Information System</title><link rel="stylesheet" href="assets/app.css"></head><body><div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark"><span></span><span></span></div><div><strong>Barangay</strong><small>information system</small></div></div><div class="portal-label"><span class="seal">✧</span><div><small>Current portal</small><strong><?= $user['role']==='resident'?'Resident portal':'Official portal' ?></strong></div><span>⌄</span></div><nav class="main-nav"><div class="nav-caption">Workspace</div><?php foreach ($nav as $key => [$label, $icon]): $target = ['dashboard'=>'index.php','portal'=>'resident_portal.php','accounts'=>'resident_accounts.php','privacy'=>'privacy.php','notifications'=>'notifications.php','staff'=>'staff_accounts.php','audit'=>'audit.php','privacy_admin'=>'privacy_admin.php'][$key] ?? ($key . '.php'); ?><a class="nav-link <?= $activePage === $key ? 'active' : '' ?>" href="<?= h($target) ?>"><span class="nav-icon"><?= $icon ?></span><span><?= h($label) ?></span><?php if($key==='documents'): ?><b>12</b><?php elseif($key==='blotters'): ?><b>5</b><?php endif; ?></a><?php endforeach; ?><div class="nav-caption">Administration</div><?php if($user['role']!=='resident'): ?><a class="nav-link <?= $activePage === 'retention' ? 'active' : '' ?>" href="retention.php"><span class="nav-icon">◷</span><span>Retention</span></a><a class="nav-link <?= $activePage === 'backup' ? 'active' : '' ?>" href="backup.php"><span class="nav-icon">⇩</span><span>Backups</span></a><?php endif; ?><a class="nav-link" href="logout.php"><span class="nav-icon">↪</span><span>Sign out</span></a></nav><div class="sidebar-bottom"><div class="help"><strong>Need a hand?</strong><small>Local capstone system</small></div><div class="user-chip"><span><?= h(strtoupper(substr($user['full_name'],0,1))) ?></span><div><strong><?= h($user['full_name']) ?></strong><small><?= h(ucfirst($user['role'])) ?></small></div></div></div></aside><main class="main-content"><header class="topbar"><div class="crumb"><span><?= $user['role']==='resident'?'Resident portal':'Official portal' ?></span><i>›</i><strong><?= h($pageTitle) ?></strong></div><div class="top-actions"><div class="search-mini">⌕ <input placeholder="Search records..." aria-label="Search records"></div><span class="bell">♢<em></em></span><span class="view-pill"><i></i> <?= h(ucfirst($user['role'])) ?> view</span></div></header><div class="page-content"><?php if($flashMessage): ?><div class="flash <?= h($flashMessage['type']) ?>"><?= h($flashMessage['message']) ?></div><?php endif; ?>
