<?php
require_once __DIR__ . '/includes/functions.php'; require_once __DIR__ . '/config/database.php'; require_once __DIR__ . '/includes/auth.php'; require_once __DIR__ . '/includes/mailer.php';
if (!system_is_setup()) { redirect('setup.php'); }
if (!empty($_SESSION['user'])) { header('Location: ' . ($_SESSION['user']['role'] === 'resident' ? 'resident_portal.php' : 'index.php')); exit; }
$error = null;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $stmt=db()->prepare('SELECT * FROM users WHERE username=? LIMIT 1');$stmt->execute([trim($_POST['username']??'')]);$user=$stmt->fetch();$expired=$user && !empty($user['account_expires_at']) && $user['account_expires_at']<date('Y-m-d');
    if (!rate_limit('login:'.($_SERVER['REMOTE_ADDR']??'unknown'), 10, 900)) { $error='Too many sign-in attempts. Please wait 15 minutes before trying again.'; }
    elseif ($user && !$expired && $user['account_status']==='active' && password_verify($_POST['password']??'', $user['password_hash'])) {
        if (empty($user['email']) || !mail_is_configured()) { $error='Password accepted, but Gmail OTP is not configured. Set the MAIL_USERNAME, MAIL_APP_PASSWORD, and MAIL_FROM_EMAIL environment values first.'; }
        else { $code=(string)random_int(100000,999999);db()->prepare('UPDATE login_challenges SET used_at=NOW() WHERE user_id=? AND used_at IS NULL')->execute([$user['id']]);db()->prepare('INSERT INTO login_challenges (user_id,code_hash,expires_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 10 MINUTE))')->execute([$user['id'],password_hash($code,PASSWORD_DEFAULT)]);if(send_login_otp($user['email'],$code)){$_SESSION['pending_user_id']=$user['id'];$_SESSION['pending_email']=$user['email'];redirect('verify_otp.php');}$error='Unable to send the verification email. Check Gmail SMTP settings and try again.'; }
        } else { audit_action('login_failed','users',$user['id'],'Invalid password or disabled account'); $error=$expired?'This resident portal account has expired. Contact the barangay office.':'Invalid username, password, or account status.'; }
}
$flash=pull_flash();
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Sign in · Barangay Information System</title><link rel="stylesheet" href="assets/app.css"></head><body class="login-page"><div class="login-card"><div class="brand login-brand"><div class="brand-mark"><span></span><span></span></div><div><strong>Barangay</strong><small>information system</small></div></div><div class="eyebrow">Local portal</div><h1>Sign in securely.</h1><p class="login-copy">Enter your password, then confirm the one-time code sent to your registered email.</p><?php if($error): ?><div class="flash error"><?= h($error) ?></div><?php endif; ?><?php if($flash): ?><div class="flash <?= h($flash['type']) ?>"><?= h($flash['message']) ?></div><?php endif; ?><form method="post" class="login-form"><input type="hidden" name="csrf" value="<?= h(csrf_token()) ?>"><label>Username<input name="username" required autocomplete="username"></label><label>Password<input type="password" name="password" required autocomplete="current-password"></label><button class="primary-button full-button" type="submit">Continue to email verification</button></form><div class="demo-note"><strong>Two-step security</strong><span>A Gmail OTP is required on every sign-in.</span></div></div></body></html>
